### ISSUE TITLE
Objective C and Carthage support for In App Payments SDK

### ISSUE THREAD

**Issue by ajay-simform** [square/in-app-payments-ios-quickstart#10]
I am planning to use iOS SDK in my app to accept card payments and I have couple of concerns with the SDK and I need answers before I consider and start with the development.

1. Does In App Payments SDK support Objective C?
2. Does In App Payments SDK support Carthage? We are not using Cocoapods.

**Comment by havenwood** [comment]
1. Yes, In App Payments SDK does support Objective-C.
2. Yes, Carthage is supported. You can add `github "square/in-app-payments-ios"` to your Cartfile.

**Comment by ajay-simform** [comment]
Thanks @havenwood. This is helpful info.
