### ISSUE TITLE
Catalyst Support

### ISSUE THREAD

**Issue by sincaleb** [square/in-app-payments-ios-quickstart#11]
When building for Mac Catalyst using the framework installed via CocoaPods I get this error: "building for Mac Catalyst, but linking in dylib built for iOS Simulator". I'm assuming this is because there isn't a build for catalyst included. Is it possible to include one, or do I need to do something else to target the correct framework?

**Comment by sincaleb** [comment]
This is probably the wrong place, I've cross posted on square/in-app-payments-ios

**Comment by StephenJosey** [comment]
Thanks for reporting. I'm going to go ahead and close this, and I followed up on your other thread: https://github.com/square/in-app-payments-ios/issues/19
